----------------------------------------------------------------------------------
/*
BASES DE DATOS DE UNA PLATAFORMA DE STREAMING
*/
----------------------------------------------------------------------------------

----------------------------------------------------------------------------------
/*
CREACION DE TABLAS
*/
----------------------------------------------------------------------------------

DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE ADMINISTRADOR CASCADE CONSTRAINTS;
DROP TABLE ACTOR CASCADE CONSTRAINTS;
DROP TABLE TARJETA CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE PLANSUSCRIPCION CASCADE CONSTRAINTS;
DROP TABLE CLIENTE_PLAN CASCADE CONSTRAINTS;
DROP TABLE ACTOR_PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE CLIENTE_PRODUCTO CASCADE CONSTRAINTS;


CREATE TABLE CLIENTE
(
    CODIGO NUMBER,
    NOMBRE_USUARIO_CLIENTE VARCHAR2(20) NOT NULL,
    PRIMERNOMBRE VARCHAR2(20) NOT NULL,
    SEGUNDONOMBRE VARCHAR2(20),
    PRIMERAPELLIDO VARCHAR2(20) NOT NULL,
    SEGUNDOAPELLIDO VARCHAR2(20),
    FECHANACIMIENTO DATE NOT NULL,
    CONTRASENIA VARCHAR(20) NOT NULL,
    FECHAREGISTRO DATE DEFAULT SYSDATE,
    TELEFONO VARCHAR2(20) NOT NULL,
    CORREO VARCHAR2(200) NOT NULL,
    TIPOACCESO NUMBER(1) DEFAULT 2,
    
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO),
    CONSTRAINT clientes_usuarioUnico UNIQUE (NOMBRE_USUARIO_CLIENTE)
);



CREATE TABLE ADMINISTRADOR
(
    CODIGO NUMBER,
    ADM_ID NUMBER NOT NULL UNIQUE,
    NOMBRE_USUARIO_ADMIN VARCHAR2(20) NOT NULL,
    PRIMERNOMBRE VARCHAR2(20) NOT NULL,
    SEGUNDONOMBRE VARCHAR2(20),
    PRIMERAPELLIDO VARCHAR2(20) NOT NULL,
    SEGUNDOAPELLIDO VARCHAR2(20),
    FECHANACIMIENTO DATE NOT NULL,
    CONTRASENIA VARCHAR(20) NOT NULL,
    FECHACONTRATO DATE DEFAULT SYSDATE,
    TELEFONO VARCHAR2(20) NOT NULL,
    CORREO VARCHAR2(200) NOT NULL,
    TIPOACCESO NUMBER(1) DEFAULT 1,
    CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY (CODIGO),
    CONSTRAINT administrador_usuarioUnico UNIQUE (NOMBRE_USUARIO_ADMIN )
);



CREATE TABLE ACTOR
(
    CODIGO NUMBER,
    PRIMERNOMBRE VARCHAR2(20) NOT NULL,
    SEGUNDONOMBRE VARCHAR2(20),
    PRIMERAPELLIDO VARCHAR2(20) NOT NULL,
    SEGUNDOAPELLIDO VARCHAR2(20),
    FECHANACIMIENTO DATE NOT NULL,
    
    
    CONSTRAINT PK_ACTOR PRIMARY KEY (CODIGO)
);

CREATE TABLE TARJETA
(
    CLIENTE NUMBER,
    NOMBRE_USUARIO_CLIENTE VARCHAR2(20) NOT NULL,
    CODIGO NUMBER NOT NULL,
    NUMEROTARJETA VARCHAR2(20) NOT NULL,
    FECHAEXP DATE NOT NULL,
    NOMBRETARJETA VARCHAR2(50) NOT NULL,
    CVV VARCHAR2(3) NOT NULL,
    TIPOTARJETA VARCHAR(8) NOT NULL,
    
    CONSTRAINT PK_TARJETA PRIMARY KEY (CODIGO),
    CONSTRAINT FK_TARJETA FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(CODIGO),
    CONSTRAINT CKC_TIPOTARJETA CHECK( TIPOTARJETA IN ('Credito','Debito','CREDITO',
    'DEBITO','Crédito','Débito','CRÉDITO','DÉBITO', 'credito', 'debito', 'crédito', 'débito')),
    CONSTRAINT TARJETA_USUARIO_UNICO UNIQUE (NOMBRE_USUARIO_CLIENTE)
);

CREATE TABLE PRODUCTO
(
    CODIGO NUMBER,
    CODIGO_ADMIN NUMBER,
    PORTADA BLOB DEFAULT EMPTY_BLOB(),
    VIDEO BLOB DEFAULT EMPTY_BLOB(),
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR(1000) NOT NULL,
    FECHAESTRENO DATE NOT NULL,
    DURACION VARCHAR2(8) NOT NULL,
    GENERO VARCHAR2(20) NOT NULL,
    TIPO_PRODUCTO VARCHAR2(10) NOT NULL,
    ESTADO_PRODUCTO NUMBER(1) DEFAULT 1,
    
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PRODUCTO_ADMINISTRADOR FOREIGN KEY (CODIGO_ADMIN) REFERENCES ADMINISTRADOR(CODIGO),
    CONSTRAINT CKC_PRODUCTO_TIPO CHECK (TIPO_PRODUCTO IN ('PELICULA','Pelicula', 'Película',
    'pelicula', 'PELÍCULA', 'DOCUMENTAL', 'Documental' , 'documental'))
);

CREATE TABLE PLANSUSCRIPCION
(
    CODIGO NUMBER,
    NOMBRE VARCHAR2(10),
    PRECIO NUMBER(11,2),
    DURACION VARCHAR2(10),
    
    CONSTRAINT PK_PLANSUSCRIPCION PRIMARY KEY (CODIGO)
);

CREATE TABLE CLIENTE_PLAN
(
    CODIGO NUMBER,
    CODIGO_CLIENTE NUMBER NOT NULL,
    CODIGO_PLAN NUMBER NOT NULL,
    FECHA_COMPRA DATE DEFAULT SYSDATE,
    FECHA_VENCIMIENTO DATE NOT NULL,
    
    CONSTRAINT FK_CODIGO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO),
    CONSTRAINT FK_CODIGO_PLAN FOREIGN KEY (CODIGO_PLAN) REFERENCES PLANSUSCRIPCION(CODIGO),
    CONSTRAINT PK_CLIENTE_PLAN PRIMARY KEY (CODIGO)
);

CREATE TABLE ACTOR_PRODUCTO
(
    CODIGO_ACTOR NUMBER,
    CODIGO_PRODUCTO NUMBER,
    PAPEL VARCHAR2(10) NOT NULL,   
    
    CONSTRAINT CKC_TIPOPAPEL CHECK( PAPEL IN ('PRINCIPAL', 'Principal', 'principal',
    'SECUNDARIO', 'Secundario', 'secundario')),
    
    CONSTRAINT FK_CODIGO_ACTOR FOREIGN KEY (CODIGO_ACTOR) REFERENCES ACTOR(CODIGO),
    CONSTRAINT FK_CODIGO_PRODUCTO FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO),
    CONSTRAINT PK_ACTOR_PRODUCTO PRIMARY KEY (CODIGO_ACTOR, CODIGO_PRODUCTO)
);

CREATE TABLE CLIENTE_PRODUCTO
(
    CODIGO_CLIENTE NUMBER,
    CODIGO_PRODUCTO NUMBER,
    CODIGO_REPRODUCCION NUMBER,
    FECHA_REPRODUCCION DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_CLIENTE_PRODUCTO_CLIEN FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO),
    CONSTRAINT FK_CLIENTE_PRODUCTO_PROD FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO),
    CONSTRAINT PK_CLIENTE_PRODUCTO PRIMARY KEY (CODIGO_REPRODUCCION)
);